In [4]:
import pandas as pd

semester = "spring"
year = 2023

genedCategories = {
  "ACP": "Advanced Composition",
  "CS": "Cultural Studies",
  "HUM": "Humanities & the Arts",
  "NAT": "Natural Sciences & Technology",
  "QR": "Quantitative Reasoning",
  "SBS": "Social & Behavioral Sciences",
}

dfs = []
for genedKey in genedCategories:
  url = f"https://courses.illinois.edu/gened/{year}/{semester}/{genedKey}"
  dfs.append(pd.read_html(url)[0])

df = pd.concat(dfs)

In [26]:
df["Year"] = year
df["Term"] = semester.title()
df["TermYear"] = f"{year}-{semester[0:2]}"
df

,COURSE,Unnamed: 1,TITLE,ACP,CS,COMP1,HUM,NAT,QR,SBS,Year,Term,TermYear
0,AAS 300,NaN,"Theories of Race, Gender, and Sexuality",ACP,NaN,NaN,NaN,NaN,NaN,NaN,2023,Spring,2023-sp
1,AAS 310,NaN,Race and Cultural Diversity,ACP,US,NaN,NaN,NaN,NaN,NaN,2023,Spring,2023-sp
2,AAS 370,NaN,"Immigration, Law, and Rights",ACP,NaN,NaN,NaN,NaN,NaN,NaN,2023,Spring,2023-sp
3,AAS 402,NaN,Asian American Education,ACP,US,NaN,NaN,NaN,NaN,NaN,2023,Spring,2023-sp
4,ABE 469,NaN,Industry-Linked Design Project,ACP,NaN,NaN,NaN,NaN,NaN,NaN,2023,Spring,2023-sp
...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,PSYC 322,NaN,Introduction to Intellectual Disability,NaN,NaN,NaN,NaN,NaN,NaN,BSC,2023,Spring,2023-sp
202,REHB 322,NaN,Introduction to Intellectual Disability,NaN,NaN,NaN,NaN,NaN,NaN,BSC,2023,Spring,2023-sp
203,RST 120,NaN,"Parks, Recreation, and Environments",NaN,NaN,NaN,NaN,NaN,NaN,BSC,2023,Spring,2023-sp
204,SHS 120,NaN,"Child, Comm, & Lang Ability",NaN,NaN,NaN,NaN,NaN,NaN,BSC,2023,Spring,2023-sp
205,SPED 322,NaN,Introduction to Intellectual Disability,NaN,NaN,NaN,NaN,NaN,NaN,BSC,2023,Spring,2023-sp

In [27]:
df_clean = df.sort_values("COURSE").drop_duplicates("COURSE").drop(["Unnamed: 1", "COMP1"], axis=1).rename(columns={
  "COURSE": "Course",
  "TITLE": "Course Title"
})[ ["Year", "Term", "TermYear", "Course", "Course Title", "ACP", "CS", "HUM", "NAT", "QR", "SBS"] ]
df_clean

,Year,Term,TermYear,Course,Course Title,ACP,CS,HUM,NAT,QR,SBS
0,2023,Spring,2023-sp,AAS 100,Intro Asian American Studies,NaN,US,NaN,NaN,NaN,SS
1,2023,Spring,2023-sp,AAS 105,Introduction to Arab American Studies,NaN,US,NaN,NaN,NaN,NaN
2,2023,Spring,2023-sp,AAS 120,Intro to Asian Am Pop Culture,NaN,US,NaN,NaN,NaN,NaN
3,2023,Spring,2023-sp,AAS 200,U.S. Race and Empire,NaN,US,HP,NaN,NaN,NaN
1,2023,Spring,2023-sp,AAS 201,US Racial & Ethnic Politics,NaN,US,NaN,NaN,NaN,SS
...,...,...,...,...,...,...,...,...,...,...,...
78,2023,Spring,2023-sp,UP 316,Urban Informatics II,NaN,NaN,NaN,NaN,QR2,NaN
197,2023,Spring,2023-sp,UP 330,The Modern American City,NaN,US,NaN,NaN,NaN,NaN
147,2023,Spring,2023-sp,WRIT 303,Writing Across Media,ACP,NaN,NaN,NaN,NaN,NaN
571,2023,Spring,2023-sp,YDSH 220,Jewish Storytelling,NaN,WCC,LA,NaN,NaN,NaN
239,2023,Spring,2023-sp,YDSH 320,Responses to the Holocaust,NaN,WCC,LA,NaN,NaN,NaN

In [30]:
df_clean.to_csv("gened-courses.csv", index=False)